name: build

on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Install Go
        uses: trim21/actions/setup-go@master

      - run: go build -o /dev/null ./...
        name: Build Binary
        env:
          CGO_ENABLED: '0'
