name: release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Go
        uses: trim21/actions/setup-go@master

      - run: go build -trimpath -o dist/clear-old-cache
        name: Build Binary
        env:
          CGO_ENABLED: "0"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: "ghcr.io/bangumi/clear-old-cache"
          tags: |
            type=ref,event=branch
            type=ref,event=branch,suffix=-{{ sha }}

      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
