name: release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: trim21/actions/setup-go@master

      - run: go build -trimpath -o dist/clear-old-cache
        name: Build Binary
        env:
          CGO_ENABLED: "0"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/bangumi/clear-old-cache"
          tags: |
            type=ref,event=branch
            type=ref,event=branch,suffix=-{{ sha }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
