name: Security Vulnerability Check

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yaml"
      - ".github/workflows/security.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/security.yaml"
  schedule:
    - cron: "15 3 * * 4"

jobs:
  vulnerability-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - uses: trim21/actions/setup-go@master
        with:
          cache-namespace: sec

      - run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - run: govulncheck ./...
